apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
type: Opaque
data:
  POSTGRES_DB: Q29udGFjdE1hbmFnZW1lbnREYg== 
  POSTGRES_USER: YWRtaW4=               
  POSTGRES_PASSWORD: ZzNaY0FVS2I=
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: postgres-db-pv
  labels:
    name: postgres-db-pv
spec:
  capacity: 
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-pvc
  labels:
    name: postgres-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db 
    spec:
      containers:
        - name: container-postgres-db
          image: postgres:latest
          ports:
            - name: "db-port"
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-db-storage
      volumes:
        - name: postgres-db-storage
          persistentVolumeClaim:
            claimName: postgres-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: service-postgres-db
  labels:
    app: postgres-db
spec:
  type: ClusterIP
  ports:
    - name: db-port
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-db