using System.Diagnostics.CodeAnalysis;

namespace Postech.Hackathon.Agendamentos.TestesIntegrados.Auxiliares;

[ExcludeFromCodeCoverage]
public static class BearerTokenAuxiliar
{
    public static readonly string TokenValidoPaciente = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlRlc3RlIiwiSWQiOiI1NDZkOWUxMi1mYmE0LTQ5NTctYWEwMS1kYzlkYjA5NGRjOWEiLCJyb2xlIjpbInBhY2llbnRlLnJlYWQiLCJwYWNpZW50ZS53cml0ZSIsInBhY2llbnRlX2FnZW5kYW1lbnRvLnJlYWQiLCJwYWNpZW50ZV9hZ2VuZGFtZW50by53cml0ZSJdLCJQYXBlbCI6InBhY2llbnRlIiwibmJmIjoxNzM5MDMxODgzLCJleHAiOjE3MzkwMzU0ODMsImlhdCI6MTczOTAzMTg4MywiaXNzIjoiYWRtaW4iLCJhdWQiOiJ0ZXN0ZS1icmVubyJ9.LeQYmJF6DsaxRldTD1h9LBV_bpAUFioU6sIIodvmhrw";
    public static readonly string TokenValidoMedico = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlRlc3RlIiwiSWQiOiJlNTQ2ODBkZS04YTU2LTRhNDctODhhYy0yOTI0MDMwYTA2OGIiLCJyb2xlIjpbIm1lZGljby5yZWFkIiwibWVkaWNvLndyaXRlIiwibWVkaWNvX2FnZW5kYW1lbnRvLndyaXRlIl0sIlBhcGVsIjoibWVkaWNvIiwibmJmIjoxNzM5MDMxODQzLCJleHAiOjE3MzkwMzU0NDMsImlhdCI6MTczOTAzMTg0MywiaXNzIjoiYWRtaW4iLCJhdWQiOiJ0ZXN0ZS1icmVubyJ9.cjrYi2y7YdziVQFIPBxfPMuEPfeIMctu21evIrAVkx8";
}