name: Feature Workflow

on:
    push:
        branches: ["feature/**"]

permissions:
    contents: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore
              working-directory: src

            - name: Build solution
              run: dotnet build --configuration Release --no-restore
              working-directory: src
    
    deploy_docker_hub:
      name: Push to DockerHub
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.x'

        - name: Login DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Build Image
          run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hackathon-servico-agendamento:latest -f src/Postech.Hackathon.Agendamentos.Api/Dockerfile .

        - name: Push Image
          run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/hackathon-servico-agendamento:latest            

    unit_test:
        name: Unit Tests
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore
              working-directory: testes/Postech.Hackathon.Agendamentos.TestesUnitarios

            - name: Build test project
              run: dotnet build --no-restore
              working-directory: testes/Postech.Hackathon.Agendamentos.TestesUnitarios

            - name: Run tests
              run: dotnet test --verbosity normal
              working-directory: testes/Postech.Hackathon.Agendamentos.TestesUnitarios
    
    integration_test:
        name: Integration Tests
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'

            - name: Restore dependencies
              run: dotnet restore
              working-directory: testes/Postech.Hackathon.Agendamentos.TestesIntegrados

            - name: Build test project
              run: dotnet build --no-restore
              working-directory: testes/Postech.Hackathon.Agendamentos.TestesIntegrados

            - name: Run tests
              run: dotnet test --verbosity normal
              working-directory: testes/Postech.Hackathon.Agendamentos.TestesIntegrados

    create_pr:
      name: Create Pull Request
      runs-on: ubuntu-latest
      needs: [unit_test, integration_test]
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request To Develop
        run: |
          cd $GITHUB_WORKSPACE
          gh auth login --with-token <<< "${{ secrets.PAT_TOKEN }}"
          gh pr create -B develop --title 'PR automático da branch ${{ github.head_ref || github.ref_name }} para develop' --body 'Pull Request gerado automaticamente pelo Github Actions' || gh pr edit -B develop --title 'Atualização do Pull Request gerado automaticamente pelo Github Actions' --body 'Pull Request gerado automaticamente pelo Github Actions'