name: Release Workflow

on:
    push:
        branches: ["release/**"]

permissions:
    contents: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore
              working-directory: src

            - name: Build solution
              run: dotnet build --configuration Release --no-restore
              working-directory: src
    
    unit_test:
        name: Unit Tests
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore
              working-directory: testes/Postech.Hackathon.Agendamentos.TestesUnitarios

            - name: Build test project
              run: dotnet build --no-restore
              working-directory: testes/Postech.Hackathon.Agendamentos.TestesUnitarios

            - name: Run tests
              run: dotnet test --verbosity normal
              working-directory: testes/Postech.Hackathon.Agendamentos.TestesUnitarios

    create_pr:
      name: Create Pull Request
      runs-on: ubuntu-latest
      needs: [unit_test]
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request To Main
        run: |
          cd $GITHUB_WORKSPACE
          gh auth login --with-token <<< "${{ secrets.PAT_TOKEN }}"
          gh pr create -B main --title 'PR automático da branch ${{ github.head_ref || github.ref_name }} para main' --body 'Pull Request gerado automaticamente pelo Github Actions' || gh pr edit -B main --title 'Atualização do Pull Request gerado automaticamente pelo Github Actions' --body 'Pull Request gerado automaticamente pelo Github Actions'